#spring.datasource.url=jdbc:mysql://localhost:3306/blogDB
#spring.datasource.username=root
#spring.datasource.password=admin
#spring.jpa.hibernate.ddl-auto=update

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#spring.security.user.name=Selim
#spring.security.user.password=Selim
#spring.security.user.roles=Admin


#----------------------------------------
# javalearing <- encrypt this using sha256 online
app.jwt.secret=e03b9e36299bbeccbe674889d7c175b12f5c931bb1624b7d29417d64a5807710
app-jwt-expiratin-miliseconds=60480000

spring.profiles.active=dev


